# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
# install hydra-colorlog==1.2.0
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${trainer.output_path}
  # dir: ${trainer.output_path}/${tasks.task_type}/runs/${name}_${now:%Y-%m-%d}_${now:%H-%M-%S}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${name}_${now:%Y-%m-%d}_${now:%H-%M-%S}.log

