_target_: MolecularDiffusion.runmodes.train.ModelTaskFactory_EGCL
task_type: regression
atom_vocab: ${data.atom_vocab}
condition_names: []
hidden_size: 512
act_fn:
  _target_: torch.nn.ReLU
num_layers: 5
attention: True
tanh: True
num_sublayers: 1
sin_embedding: False
aggregation_method: "sum"
dropout: 0.0
normalization: True
include_cosine: True
norm_constant: 1.0
normalization_factor: 1.0
chkpt_path: None

# specific to regression
task_learn: [gap]
criterion: mse
metric: [mae]
num_mlp_layer: 3
mlp_dropout: 0.2